import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: '/full-layout/branch',
    title: 'Plants',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_MASTERDATA'],
  },
  {
    path: '/full-layout/item',
    title: 'Items',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_MASTERDATA'],
  },
  {
    path: '/full-layout/user',
    title: 'Users',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_USERMANAGEMENT'],
  },
];
