import { RouteInfo } from './sidebar.metadata';

export const ROUTES: RouteInfo[] = [
  {
    path: '/full-layout/cabinet',
    title: 'Cabinets',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_USERMANAGEMENT'],
  },
  {
    path: '/full-layout/user-list',
    title: 'Users',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_USERMANAGEMENT'],
  },
  {
    path: '/full-layout/branch',
    title: 'Plants',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: false,
    authorities: ['ROLE_ADMIN', 'ROLE_MASTERDATA'],
  },
  {
    path: '/full-layout/item',
    title: 'Items',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_MASTERDATA'],
  },
  {
    path: '/full-layout/customer',
    title: 'Customers',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN', 'ROLE_USERMANAGEMENT'],
  },
  {
    path: '/full-layout/stk-trans-receipt',
    title: 'STK Receipt',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: false,
    authorities: ['ROLE_ADMIN', 'ROLE_MASTERDATA'],
  },
  {
    path: '/full-layout/stk-trans-issue',
    title: 'STK Issue',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: false,
    authorities: ['ROLE_ADMIN', 'ROLE_MASTERDATA'],
  },
  {
    path: '/full-layout/stk-trans-header',
    title: 'Stock Transactions',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: true,
    authorities: ['ROLE_ADMIN'],
  },
  {
    path: '/full-layout/reports',
    title: 'Reports',
    icon: 'ft-layout',
    class: '',
    badge: '',
    badgeClass: '',
    isExternalLink: false,
    submenu: [],
    isMenu: false,
    authorities: ['ROLE_ADMIN', 'ROLE_REPORTS'],
  },
];
